### ISSUE TITLE
Why do `EndpointReceiver::recv*` functions take ownership of BytesMut?

### ISSUE THREAD

**Issue by samcday** [surban/usb-gadget#3]
Wouldn't it make more sense to take a reference? My understanding is that, as of right now, every packet received over a Custom endpoint results in an allocation. For example, your upc crate is [performing an allocation](https://docs.rs/bytes/latest/src/bytes/bytes_mut.rs.html#142-144) every time a [packet is received](https://github.com/surban/upc/blob/bb0ab99/src/device.rs#L330).

**Comment by surban** [comment]
usb-gadget places the passed BytesMut into the end of the receive queue which is managed by the kernel. When a packet is received the BytesMut in front of the queue is filled with the received data and returned. Thus, the passed-in and returned BytesMut are not the same object.

**Comment by samcday** [comment]
Also, I'm wondering if you could shed some light on *why* the design is the way it is right now. Is it because of how FunctionFS works internally or something?

More pointedly, would it be possible to implement the `EndpointReceiver` in such a way that it can `recv` directly into a `&mut [u8]`?

For my particular use case this would be optimal - since then I could just read from the endpoint FIFO directly into a framebuffer (allocated with gbm or something, such that it resides in VRAM or is otherwise ready to be DMA'd).

**Comment by surban** [comment]
The main reason for this is performance. 

To ensure good USB transfer performance it is important that the send and receive queues of the UDC are always filled. If we would wait for a receive buffer to get filled before posting the next buffer, this could result in a bottleneck. It is also the reason why I use AIO instead of synchronous IO (read, write calls).

Have you considered using [`BytesMut::split`](https://docs.rs/bytes/1.5.0/bytes/struct.BytesMut.html#method.split) and [`BytesMut::unsplit`](https://docs.rs/bytes/1.5.0/bytes/struct.BytesMut.html#method.unsplit) for improving performance? This should at least allow you to receive multiple USB transfer in one continuous buffer. However, I am not sure if Linux guarantees that a posted buffer will be filled completely.

Completely avoiding copies might be difficult with the current architecture since [`BytesMut`] cannot currently be used to manage a pre-allocated buffer. I don't know if this is easily fixable, but if so, the best solution would probably be to extend the `bytes` crate appropriately. 

Another solution might be for `usb-gadget` to expose the file descriptor of the endpoint file, so that buffer management can be done manually using unsafe code, for such high-performance cases as yours.

**Comment by samcday** [comment]
Yeah after further work on my crate I realized how the behaviour is supposed to work a bit better.

I understand now why the first few times you call `recv` with a Buffer, you get a `None` back. It wasn't so bad to implement something that is reasonably performant: I just keep a `Vec<BytesMut>` handy and pop one off the end to provide to usb-gadget. Then, when I'm done reading one that I get back, I push it on the end of that Vec.

The issue is that these buffers aren't contiguous, as you've already pointed out. I did look at split_to and I considered that an option of last resort since it would be kinda fussy to work with such an API to achieve what I want.

> However, I am not sure if Linux guarantees that a posted buffer will be filled completely.

Yeah I guess that would indeed be an issue. I imagine that if the USB link is under pressure, that particular Bulk endpoint may not receive the full 512 bytes it would normally get (on a 3.0 link at least).

> Another solution might be for usb-gadget to expose the file descriptor of the endpoint file

Yeah, I considered this because I noticed there's a few AIO crate options on crates.io. I haven't evaluated any of them to see if they might have the kind of API I'm looking for. But I figured if I found something, it would be a fairly simple patch in `usb-gadget` to allow the underlying FD to be retrieved. Glad to hear you think that's feasible as well :+1:

**Comment by surban** [comment]
> > However, I am not sure if Linux guarantees that a posted buffer will be filled completely.
> 
> Hmm, I guess that would indeed be an issue. I imagine that if the USB link is under pressure, that particular Bulk endpoint may not receive the full 512 bytes it would normally get (on a 3.0 link at least).
> 

I guess you would have to figure that out first. If this is the case, then copies are probably unavoidable.

**Comment by samcday** [comment]
Hmm, based on my understanding of how [`f_fs.c` handles reads](https://github.com/torvalds/linux/blob/8c94ccc/drivers/usb/gadget/function/f_fs.c#L827), it seems that anything other than receiving exactly as many bytes as you requested is an error.

I also don't see anything in the `io_event` struct or the signalling in `aio_get_events` that would indicate a buffer underrun.

**Comment by surban** [comment]
Okay, what do you think about extending `BytesMut` so that it can be constructed like [`slice::from_raw_parts`](https://doc.rust-lang.org/std/slice/fn.from_raw_parts.html)?

**Comment by samcday** [comment]
Alternatively, what do you think about such an api:

```
pub fn recv_exact(&mut self, buf: &mut [u8], len: usize) -> Result<()>;
```

The implementation will be responsible for submitting as many AIO operations as is necessary to satisfy the request, ensuring that each submitted request is the `max_packet_size` (or less for the final submission).

So for example, if I call:

```
let buf [u8; 51201] = [0; 51201];
ep.recv_exact(&mut buf, 51201).unwrap();
```

Here's what I expect to happen in the background:

* 10 (or whatever the queue_len of the AIO `Driver` has been configured with) AIO tasks are immediately submitted.
* (Ideally, all 10 are submitted in one request, currently it seems the driver is submitting them one at at time, but the number of syscalls can be reduced by batching them up)
* As the tasks come back, subsequent tasks are submitted, until the requested amount of bytes has been read.
* The final task submitted would be for 1 byte (assuming the EP max size is the typical 512).
* If at any point AIO returns an error, then all pending tasks are cancelled, and the caller is notified.

My understanding of the bulk endpoint is that you'll typically know exactly how much you're going to read from it, because you've received some kind of signal via a control message on EP0 to inform you that data is on the way. So in most cases, the current API is actually maybe a little too low level - you don't want to be juggling N buffers and worrying about keeping the underlying AIO task queue saturated, you just want to read N bytes from the endpoint (ideally as fast as possible).

I'm pretty sure the API as proposed could work async, as well. In fact it might be better to only implement it as async, and the sync API runs the async func in a single thread executor.

**Comment by samcday** [comment]
The advantages of this proposed API I think are such:

1) it's simpler for the cases where you know up front exactly how many bytes you need to read from the bulk endpoint (which as I noted before, I think is basically always the case? I'm curious what you think about that).
2) it ensures that the logic to do high performance reads with AIO is thought through and implemented *once*, in the library, rather than being something that every user needs to understand and deal with
3) it allows the buffer to be any arbitrary writable segment of memory somewhere (which was what I originally started this issue to ask about! xD)

**Comment by samcday** [comment]
If you think this sounds sane, I'm happy to take a stab at implementing such a thing. Let me know!

**Comment by surban** [comment]
> Alternatively, what do you think about such an api:
> 
> ```
> pub fn recv_exact(&mut self, buf: &mut [u8], len: usize) -> Result<()>;
> ```
> 

The `len` parameter is unnecessary, since a slice in Rust already knows its length.

> I'm pretty sure the API as proposed could work async, as well. In fact it might be better to only implement it as async, and the sync API runs the async func in a single thread executor.

How do you plan on handling cancellation? In Rust a Future may be dropped at any time, thus `buf` might be dropped as well; but you have already sent a pointer into `buf` to the AIO subsystem of the kernel which might now perform writes to dangling pointers.

**Comment by surban** [comment]
> If you think this sounds sane, I'm happy to take a stab at implementing such a thing. Let me know!

Generally I like the idea, provided that the existing API stays available.

I think that your approach will work out fine for the non-async case. However, providing an async function that takes a reference to a buffer and interacts with the AIO subsystem might be challenging in current-day Rust.

**Comment by surban** [comment]
You might want to have a look at the io_uring implementation approaches for Rust. I have not followed them deeply, but I think they are facing similar problems.

**Comment by samcday** [comment]
> However, providing an async function that takes a reference to a buffer and interacts with the AIO subsystem might be challenging in current-day Rust.

Yeah I've been thinking through how this would work but I'm pretty sure it'll be fine. This is what [pinning](https://rust-lang.github.io/async-book/04_pinning/01_chapter.html) is for. When you call an async func with a slice, the lifetime of that slice is guaranteed to last as long as the future does.

Also, I feel like my idea is validated somewhat, because tokio [AsyncRead](https://docs.rs/tokio/1.36.0/tokio/io/trait.AsyncRead.html) exists.

>  but you have already sent a pointer into buf to the AIO subsystem of the kernel which might now perform writes to dangling pointers.

The [`io_destroy`](https://man.archlinux.org/man/io_destroy.2.en) syscall blocks until all pending IO request is definitely cleaned up. In the case of a single pending iocb, [`io_cancel`](https://man.archlinux.org/man/io_cancel.2) seems to also do the same but it might need extra care since it can potentially require retries on `EAGAIN`. Not sure if blocking the `Drop` on a Future until the underlying `io_cancel` succeeds will be problematic. I'll be sure to do some tests.

> You might want to have a look at the io_uring implementation approaches for Rust. I have not followed them deeply, but I think they are facing similar problems.

I did exactly this earlier today. Sadly, it seems that io_uring doesn't support FunctionFS yet (or the other way around?). Specifically, I tried the example shown here: https://crates.io/crates/io-uring, using the file descriptor for the endpoint. It seemed to not do anything. Maybe I just didn't test it properly. I was really hoping io_uring might work once I thought of it, because there's already much better ecosystem support for uring than there is for Linux AIO.

As a side rant, while thinking about this I realized that actually the perfect API for my need already exists. Are you ready for it? It's called [std::io::Read](https://doc.rust-lang.org/std/io/trait.Read.html), haha! I already know exactly how much data I wish to read, and I just want to read it into a buffer. `read_exact` does exactly that, submitting the request to the kernel as a single syscall.

... Problem is, it seems that somewhere deep in the kernel, I'm running into [this error](https://github.com/torvalds/linux/blob/v6.6/drivers/usb/chipidea/udc.c#L521) with the particular UDC hardware I'm testing with. My understanding is that udc/core is employing scatter-gather to satisfy my `read` syscall, but somehow it ends up providing the low-level UDC driver with a chunk of memory that isn't page aligned.

Oh well.

**Comment by samcday** [comment]
> Generally I like the idea, provided that the existing API stays available.

The way I'm currently planning to go ahead with this idea is to implement a separate crate that wraps Linux AIO in an async API. It turns out the API to get an FD for an Endpoint [already exists](https://github.com/surban/usb-gadget/blob/master/src/function/custom/mod.rs#L1038), so no changes to `usb-gadget` should be necessary.
