### ISSUE TITLE
Set USB port max current to 900 mA on USB 3.0

### ISSUE THREAD

**Issue by FallingSnow** [surban/usb-gadget#8]
Shouldn't the max power consumption for a USB 3 port be more than 500 mA? Or is this maxed to 500 mA by the linux gadget API? Or if the API only works on USB 2 ports?

https://github.com/surban/usb-gadget/blob/5282909742bf5e613e5481bf26c87b31cc4c4b4e/src/gadget.rs#L196

> The amount of current draw for SuperSpeed devices are increased to 150 mA for low-power devices and 900 mA for high-power devices when operating in SuperSpeed mode.

https://www.maxrev.de/files/2014/08/usb_3_0_english.pdf - Section 9.2.5.1

**Comment by surban** [comment]
Yes, the current setting was actually wrong. It should be fixed now.
