### ISSUE TITLE
Add a way for inserting custom descriptors?

### ISSUE THREAD

**Issue by Berghopper** [surban/usb-gadget#9]
Hi, I'm trying to work on a project that can emulate an xbox 360 controller, which has a slightly weird setup.
Mainly, for each interface on the controller, there's some unknown (possibly hid, but no valid to hid spec) class descriptor.
This unknown class descriptor has to be send after the interface descriptor, but before the endpoints.

I initially tried this in python, but wanted to change over to rust. The lib I used there has a 'class_descriptor_list' where it builds its descriptors before writing them.

ref to lib: https://github.com/vpelletier/python-functionfs/blob/c970265f6058982b68a028adeef5621b19a760b5/functionfs/__init__.py#L174
ref on xbox data: https://www.partsnotincluded.com/understanding-the-xbox-360-wired-controllers-usb-data/

Here's my wip as a gist: https://gist.github.com/Berghopper/44629d60708714d1dd66ebb3a6f30458

I can at least get the device recognized, but can't seem to progress past this point, any help with this would be great!
(kind of new to usb gadgets/usb programming and rust in general)

edit1; I also only get a  bind and enable event, it seems like the host never sends a request for setup?

**Comment by Berghopper** [comment]
Also another small question, as I'm not sure I have my endpoints configured correctly;

- Is there any way to use `config0_setup`, as seen here in your code?:  https://github.com/surban/usb-gadget/blob/556727253681a541aa01a28c34bf969f9dea343b/src/function/custom/mod.rs#L488

Also I'm not entirely sure what this bool seems to do, it abstracts away the first inerface setup correct?

**Comment by surban** [comment]
>     * Is there any way to use `config0_setup`, as seen here in your code?:  https://github.com/surban/usb-gadget/blob/556727253681a541aa01a28c34bf969f9dea343b/src/function/custom/mod.rs#L488

When this flag is enabled, FunctionFS userspace drivers can process non-standard control requests in configuration 0.
See https://www.spinics.net/lists/linux-usb/msg142984.html for how this was introduced.

I have never seen any code using it. You probably shouldn't use it unless there is a very specific need.

**Comment by surban** [comment]
I have added custom descriptor support. Please test with version 0.7.3.

Use `Interface::with_custom_desc` to add a custom descriptor after the interface descriptor.
